import './globals.css';
import { ClerkProvider } from '@clerk/nextjs';
import type { Metadata } from 'next';
import { nunito } from './fonts';
import Header from './_components/ui/header/Header';
import Sidebar from './_components/ui/sidebar/Sidebar';

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<ClerkProvider>
			<html lang='en'>
				<body className={nunito.className}>
					<div className='h-screen flex'>
						<Sidebar />
						<div className='w-11/12 h-full bg-stone-300'>
							<Header />
							<main>{children}</main>
						</div>
					</div>
				</body>
			</html>
		</ClerkProvider>
	);
}
