import '../globals.css';
import { ClerkProvider } from '@clerk/nextjs';
import type { Metadata } from 'next';
import { nunito } from './fonts';
import Header from '../_components/ui/header/Header';
import Sidebar from '../_components/ui/sidebar/Sidebar';

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	const appearanceObj = {
		elements: {
			card: 'bg-stone-900 p-8',
			headerTitle:
				'text-transparent text-4xl bg-orange-gradient-right bg-clip-text font-semibold',
			headerSubtitle: 'hidden',
			formFieldLabel: 'text-stone-300 font-semibold',
			formFieldInput: 'text-stone 900 font-semibold',
			formButtonPrimary: 'bg-orange-600 text-stone-900 font-semibold',
			footerActionText: 'text-stone-300 font-semibold',
			footerActionLink: 'text-orange-600 font-semibold',
		},
	};

	return (
		<ClerkProvider appearance={appearanceObj}>
			<html lang='en'>
				<body className={nunito.className}>
					<div className='flex'>
						<Sidebar />
						<div className='w-11/12'>
							<Header />
							<main>{children}</main>
						</div>
					</div>
				</body>
			</html>
		</ClerkProvider>
	);
}
