name: Behavior when feature branch is deleted

on:
  push:
    branches:
      - 'feature/**'
    paths-ignore:
      - '**' # This will make the job run only when a branch is deleted

jobs:
  handleBranchDeletion:
    if: github.event.deleted == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Handle feature branch deletion
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          BRANCH_NAME="${{ github.ref }}"
          PR_NUMBER=$(gh pr list --base $BRANCH_NAME --json number --jq '.[0].number')

          # Fetch commits of the branch
          COMMITS=$(gh pr view $PR_NUMBER --json commits --jq '.commits.nodes[] | .commit.message')

          # Update PR description
          PR_BODY="$BRANCH_NAME has the following commits:\n\n$COMMITS"
          gh pr edit $PR_NUMBER --body "$PR_BODY"

          # Close the PR
          gh pr close $PR_NUMBER

          # Delete the remote branch
          git push origin --delete $BRANCH_NAME
