name: Behavior when feature branch is deleted

on:
  push:
    branches-ignore:
      - 'feature/**'

jobs:
  handleBranchDeletion:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Handle feature branch deletion
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Check if the feature branch still exists on the remote
          EXISTS=$(git ls-remote --heads origin | grep ${{ github.ref }})

          # If the branch exists on the remote, exit
          if [[ -n "$EXISTS" ]]; then
            echo "Branch ${{ github.ref }} still exists on the remote. Exiting."
            exit 0
          fi

          PR_NUMBER=$(gh pr list --base ${{ github.ref }} --json number --jq '.[0].number')

          # If PR doesn't exist for the branch, exit
          if [[ -z "$PR_NUMBER" ]]; then
            echo "No PR found for branch ${{ github.ref }}. Exiting."
            exit 0
          fi

          # Fetch commits of the branch
          COMMITS=$(gh pr view $PR_NUMBER --json commits --jq '.commits.nodes[] | .commit.message')

          # Update PR description
          PR_BODY="${{ github.ref }} has the following commits:\n\n$COMMITS"
          gh pr edit $PR_NUMBER --body "$PR_BODY"

          # Close the PR
          gh pr close $PR_NUMBER
