name: Behavior when branch is deleted

on:
  push:
    branches:
      - dev

jobs:
  handleFeatureBranch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install GitHub CLI
        run: |
          curl -sSL https://github.com/cli/cli/releases/download/v2.32.1/gh_2.32.1_linux_amd64.deb -o gh.deb
          sudo apt install ./gh.deb
          rm gh.deb

      - name: Get merged branch name
        id: get-branch
        run: |
          BRANCH_NAME=$(git log --merges -n 1 --pretty=%B | tail -1 | cut -d ' ' -f2)
          echo "Merged branch: $BRANCH_NAME"
          echo "::set-output name=branch::$BRANCH_NAME"

      - name: Close PR and delete branch
        if: startsWith(steps.get-branch.outputs.branch, 'feature/')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh pr close ${{ steps.get-branch.outputs.branch }} --delete-branch
