name: Behavior when branch is deleted

on:
  push:
    branches:
      - dev

jobs:
  handleFeatureBranch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Get merged branch name
        id: get-branch
        run: |
          CURRENT_BRANCH=$(git rev-parse --abbrev-ref HEAD)
          MERGE_MESSAGE=$(git log ${{ github.sha }} -n 1 --merges --pretty="%s")
          BRANCH_NAME=$(echo $MERGE_MESSAGE | sed -n "s/Merge branch '\(.*\)' into $CURRENT_BRANCH/\1/p")
          echo "branch=$BRANCH_NAME" >> $GITHUB_OUTPUT

      - name: Close PR and delete branch
        if: steps.get-branch.outputs.branch != '' && startsWith(steps.get-branch.outputs.branch, 'feature/')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Find the PR associated with the branch
          PR_NUMBER=$(curl -s -H "Authorization: token $GITHUB_TOKEN" \
                          -H "Accept: application/vnd.github.v3+json" \
                          https://api.github.com/repos/Consciously/con-time-tasker/pulls?state=open \
                          | jq '.[] | select(.head.ref == "${{ steps.get-branch.outputs.branch }}").number')

          # Close the PR
          if [ ! -z "$PR_NUMBER" ]; then
            curl -s -X PATCH -H "Authorization: token $GITHUB_TOKEN" \
                          -H "Accept: application/vnd.github.v3+json" \
                          https://api.github.com/repos/Consciously/con-time-tasker/pulls/$PR_NUMBER \
                          -d '{"state": "closed"}'
          fi

          # Delete the branch
          curl -s -X DELETE -H "Authorization: token $GITHUB_TOKEN" \
                          -H "Accept: application/vnd.github.v3+json" \
                          https://api.github.com/repos/Consciously/con-time-tasker/git/refs/heads/${{ steps.get-branch.outputs.branch }}
