name: Create pull request when creating a feature branch

on:
  push:
    branches:
      - 'feature/**'

jobs:
  createPullRequest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Create or update pull request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: '${{ github.event.head_commit.message }}'
          title: '${{ github.event.head_commit.message }}'
          body: '- ${{ github.event.head_commit.message }}'
          branch: '${{ github.ref }}'
          base: 'main'
          labels: 'automated-pr'
